CXX = g++
C= gcc
MPICXX = mpic++

STOCHKITHOME = $(STOCHKIT_HOME)
STOCHKIT_SRC = $(STOCHKITHOME)/src

STOCHKIT_DRIVER = $(STOCHKITHOME)/src/drivers
STOCHKIT_MODEL_PARSER = $(STOCHKITHOME)/src/model_parser
STOCHKIT_OUTPUT = $(STOCHKITHOME)/src/output
STOCHKIT_SOLVER = $(STOCHKITHOME)/src/solvers
STOCHKIT_UTILITY = $(STOCHKITHOME)/src/utility
STOCHKIT_INCLUDE = -I$(STOCHKIT_DRIVER) -I$(STOCHKIT_MODEL_PARSER) \
			-I$(STOCHKIT_OUTPUT) -I$(STOCHKIT_SOLVER) -I$(STOCHKIT_UTILITY)

STOCHKIT_BIN = $(STOCHKITHOME)/bin
STOCHKIT_OBJ = $(STOCHKITHOME)/obj
STLIB_PATH=$(STOCHKITHOME)/libs
BOOST_PATH=$(STOCHKITHOME)/libs/boost_1_53_0
BOOSTLIB_PATH=$(STOCHKITHOME)/libs/boost_1_53_0/stage/lib
BOOSTBIN_PATH=$(STOCHKITHOME)/bin/lib
LIBXMLINC_MAC_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/libxml2
LIBXMLLIB_MAC_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/libxml2
LIBXMLINC_LINUX_PATH=/usr/include/libxml2
LIBXMLLIB_LINUX_PATH=/usr/include/libxml2
LIBXML_LIB=xml2

INCLUDE_PATH=-I$(STOCHKIT_UTILITY) -I$(STOCHKIT_OUTPUT) -I$(STOCHKIT_MODEL_PARSER) -I$(STOCHKIT_SOLVER) \
		-I$(STOCHKIT_DRIVER) -I$(STLIB_PATH) -I$(BOOST_PATH) \
		-I$(LIBXMLINC_MAC_PATH) -I$(LIBXMLINC_LINUX_PATH)

CXXFLAG = -O3 -Wall -Wextra
OPTFLAGS =
CPP_OPTIONS = $(CPPFLAG) $(INCLUDE_PATH)

LDFLAGS = 
LINK_PATH=-L$(BOOSTLIB_PATH) -L$(LIBXMLLIB_MAC_PATH) -L$(LIBXMLLIB_LINUX_PATH) -Wl,-rpath,$(BOOSTLIB_PATH)
LINK_LIBXML=-l$(LIBXML_LIB)
LINK_BOOST_PROGRAM_OPTIONS = -lboost_program_options
LINK_BOOST_THREAD = -lboost_thread
LINK_BOOST_FILESYSTEM = -lboost_filesystem
LINK_BOOST_SYSTEM = -lboost_system
LINK_LIBS= $(LINK_LIBXML) $(LINK_BOOST_PROGRAM_OPTIONS) $(LINK_BOOST_THREAD)  $(LINK_BOOST_FILESYSTEM)  $(LINK_BOOST_SYSTEM)

LINK_OPTIONS = $(LINK_PATH) $(LINK_LIBS) -lm

CXX_COMPILE = $(CXX) -c $(OPTFLAGS) $(CXXFLAG) $(INCLUDE_PATH)
CXX_LINK = $(CXX) $(LDFLAGS) 

ALLOPTIONS = $(CXXFLAG) $(INCLUDE_PATH) $(LINK_PATH) $(LINK_LIBS)

COMPILE_ONLY_OPTIONS = $(CXXFLAG) $(INCLUDE_PATH)
